services:
  postgres:
    image: postgres:16
    container_name: timetracker_postgres
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: timetracker_dev
    ports:
      - "5637:5432"
    volumes:
      - postgres_data_tt:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data_tt:
